"""add_api_usage_log

Revision ID: 3dd422971fed
Revises: 696bf8d24411
Create Date: 2026-06-05 19:00:45.046766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd422971fed'
down_revision: Union[str, None] = '696bf8d24411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_name', sa.String(length=50), nullable=False),
    sa.Column('called_at', sa.DateTime(), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=True),
    sa.Column('deliveries_updated', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_usage_log')
    # ### end Alembic commands ###
