"""Add PlayerRegistry and PlayerMergeQueue

Revision ID: 696bf8d24411
Revises: 0002
Create Date: 2026-06-05 01:52:03.053260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696bf8d24411'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_merge_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('raw_name', sa.String(length=250), nullable=False),
    sa.Column('matched_canonical', sa.String(length=250), nullable=False),
    sa.Column('fuzzy_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_registry',
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('unique_name', sa.String(length=250), nullable=False),
    sa.Column('canonical_name', sa.String(length=250), nullable=False),
    sa.Column('key_cricinfo', sa.String(length=50), nullable=True),
    sa.Column('key_espn', sa.String(length=50), nullable=True),
    sa.Column('key_cricbuzz', sa.String(length=50), nullable=True),
    sa.Column('key_bigbash', sa.String(length=50), nullable=True),
    sa.Column('key_crichq', sa.String(length=50), nullable=True),
    sa.Column('key_opta', sa.String(length=50), nullable=True),
    sa.Column('key_nvplay', sa.String(length=50), nullable=True),
    sa.Column('key_cricsheet', sa.String(length=50), nullable=True),
    sa.Column('key_rhino', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('identifier')
    )
    with op.batch_alter_table('player_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_registry_canonical_name'), ['canonical_name'], unique=False)

    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.alter_column('total_matches',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cricsheet_identifier', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_players_cricsheet_identifier'), ['cricsheet_identifier'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_cricsheet_identifier'))
        batch_op.drop_column('cricsheet_identifier')

    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.alter_column('total_matches',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('player_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_registry_canonical_name'))

    op.drop_table('player_registry')
    op.drop_table('player_merge_queue')
    # ### end Alembic commands ###
